// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"information/notary-information/index":{"path":"information/notary-information","id":"information/notary-information/index","parentId":"@@/global-layout"},"works/recognition/index":{"path":"works/recognition","id":"works/recognition/index","parentId":"@@/global-layout"},"works/recognition/info":{"path":"works/recognition/info","id":"works/recognition/info","parentId":"@@/global-layout"},"information/index":{"path":"information","id":"information/index","parentId":"@@/global-layout"},"works/index":{"path":"works","id":"works/index","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"login":{"path":"login","id":"login","parentId":"@@/global-layout"},"user":{"path":"user","id":"user","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'information/notary-information/index': React.lazy(() => import(/* webpackChunkName: "src__pages__information__notary-information__index" */'../../../src/pages/information/notary-information/index.tsx')),
'works/recognition/index': React.lazy(() => import(/* webpackChunkName: "src__pages__works__recognition__index" */'../../../src/pages/works/recognition/index.tsx')),
'works/recognition/info': React.lazy(() => import(/* webpackChunkName: "src__pages__works__recognition__info" */'../../../src/pages/works/recognition/info.tsx')),
'information/index': React.lazy(() => import(/* webpackChunkName: "src__pages__information__index" */'../../../src/pages/information/index.tsx')),
'works/index': React.lazy(() => import(/* webpackChunkName: "src__pages__works__index" */'../../../src/pages/works/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'login': React.lazy(() => import(/* webpackChunkName: "src__pages__login" */'../../../src/pages/login.tsx')),
'user': React.lazy(() => import(/* webpackChunkName: "src__pages__user" */'../../../src/pages/user.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/doulu/Documents/2026/umi-demo/src/layouts/index.tsx')),
},
  };
}
