// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/doulu/Documents/2026/umi-demo/src/models/counterModel';
import model_2 from '/Users/doulu/Documents/2026/umi-demo/src/models/user';

export const models = {
model_1: { namespace: 'counterModel', model: model_1 },
model_2: { namespace: 'user', model: model_2 },
} as const
